<main class="container-fluid">
    <div class="container-fluid termPage py-4 justify-content-start">
    <div class="pageTitleSection pb-3">
            <h3 class="h3 color-azul fw-bold">Términos y condiciones</h3>
        </div>
        <div class="container-fluid totalContent rounded">
            <div class="container-fluid py-4">
                <div class="itemsTerms py-2">
                    <h2 class="h5 color-azul fw-bold">1. ACEPTACIÓN DE LAS CONDICIONES GENERALES DE CONTRATACIÓN</h2>
                    <p class="text-term color-azul">Estas condiciones han sido actualizadas el 05/04/2021. Estas son las Condiciones Generales para que los usuarios de Internet acceden a los contenidos y servicios que MUNDO LIBRO pone a su disposición. El usuario al dar al botón "Leí y acepto los términos y condiciones" en el proceso de acceso a los contenidos del sitio admite haber leído las presentes Condiciones Generales y expresa su adhesión plena y sin reservas a todas y cada una de ellas. Asimismo, debido a que ciertos servicios y contenidos ofrecidos través del sitio pueden contener normas específicas que reglamentan y complementan a las presentes Condiciones Generales, se recomienda a los usuarios tomar conocimiento específico de ellas. Además de las presentes Condiciones Generales y las normas que los complementan, existen unas condiciones de uso del sitio detalladas en el Reglamento general de MUNDO LIBRO que todo usuario debe respetar y que se entenderá conocido por todos los usuarios del sitio.</p>
                </div>

                <div class="itemsTerms py-2">
                    <h2 class="h5 color-azul fw-bold">2. OBJETO</h2>
                    <p class="text-term color-azul"><b>2.1.</b> El objeto de las presentes Condiciones Generales es que los Usuarios tomen conocimiento de las condiciones de navegación y acceso a los distintos contenidos ofrecidos en el sitio y, eventualmente contraten servicios y/o adquieran productos a través del sitio. <b>2.2.</b> Las operaciones de venta y entrega de productos editoriales están restringidas al territorio de la República Argentina.</p>
                </div>

                <div class="itemsTerms py-2">
                    <h2 class="h5 color-azul fw-bold">3. EVENTUALES PARTES CONTRATANTES</h2>
                    <p class="text-term color-azul">En caso que un usuario adquiera un producto y/o un servicio de los ofrecidos en el sitio, las partes contratantes serán de una parte, MUNDO LIBRO con CUIT Nº 30-71695271-8 y con domicilio a estos efectos en la calle Av. 3 de Abril, Corrientes Capital, República Argentina cuya actividad principal consiste en la venta al por menor de libros y la prestación de servicios conexos, contando con los medios y autorizaciones necesarios; y de otra, cualquier persona física, de 18 años en adelante, o jurídica, destinataria de los contenidos, productos y servicios ofrecidos en el sitio a cambio de las contraprestaciones económicas que en cada caso se establecieran, según lo dispuesto en las presentes Condiciones Generales y en las normas específicas que reglamentan y complementan a las presentes Condiciones Generales.</p>
                </div>

                <div class="itemsTerms py-2">
                    <h2 class="h5 color-azul fw-bold">4. CONTENIDOS DEL SITIO</h2>
                    <p class="text-term color-azul">Los contenidos, servicios y productos a los que se refiere el objeto de las presentes Condiciones Generales son todos los que se incluyen en el sitio, a los que el usuario accede directamente.</p>
                </div>

                <div class="itemsTerms py-2">
                    <h2 class="h5 color-azul fw-bold">5. TARIFAS Y PAGOS</h2>
                    <p class="text-term color-azul"><b>5.1.</b> En caso de corresponder, el usuario siempre conocerá el precio y la modalidad de contratación de cada producto en el momento en el que proceda a su adquisición, viniendo éstos determinados de manera clara en el sitio. <b>5.2.</b> MUNDO LIBRO podrá en cualquier momento modificar las tarifas o términos de comercialización vigentes los que serán debidamente informados por MUNDO LIBRO. <b>5.3.</b> El usuario que desee contratar el acceso a los contenidos y servicios pagos de MUNDO LIBRO deberá abonar la tarifa correspondiente a través de los medios que a tal efecto se le indican en el sitio en cada momento. El cargo le será cobrado, tal como consta en las condiciones de cada producto, según el medio utilizado para el pago. Con carácter general, los cargos se realizarán al inicio de la contratación que realice el usuario. <b>5.4.</b> MUNDO LIBRO no asume responsabilidad alguna por el medio de pago elegido por los usuarios. Los medios de pago son elegidos libremente por los usuarios, por lo que cada uno de ellos renuncia a efectuarle a MUNDO LIBRO cualquier tipo de reclamo que tuviera algún tipo de relación con el medio de pago elegido. Asimismo, los usuarios reconocen que MUNDO LIBRO se reserva el derecho a no brindar los servicios y entregar los productos que no hayan sido efectivamente cobrados, debido a la falta de pago de cualquiera de las empresas prestadoras de los medios de pago. Ello, independientemente que los usuarios hubieren efectivamente realizado el pago a través del medio de pago en cuestión. <b>5.5.</b> Si el usuario tiene alguna duda referente al pago, si se han producido modificaciones en el medio de pago empleado, si cree que alguien ha utilizado sus datos de pago indebidamente o que alguien ha accedido al producto que hubiera contratado en el sitio sin su consentimiento, deberá ponerse en contacto con el Centro de Atención al Cliente a través de los canales que se ponen a su disposición indicados el sitio.</p>
                </div>

                <div class="itemsTerms py-2">
                    <h2 class="h5 color-azul fw-bold">6. FACTURACION</h2>
                    <p class="text-term color-azul">Las facturas respectivas se emitirán en forma digital, las cuales serán enviadas al usuario a su correo electrónico, estando a su vez disponibles para ser consultadas desde su cuenta personal, debiendo para ello crear un usuario de registro o loguearse en el caso de ya contar con un usuario registrado. La factura se considerará aceptada si no es impugnada por el usuario dentro de los diez (10) días de recibida.</p>
                </div>

                <div class="itemsTerms py-2">
                    <h2 class="h5 color-azul fw-bold">7. PROTECCIÓN DE DATOS PERSONALES</h2>
                    <p class="text-term color-azul">MUNDO LIBRO utilizará la información para los siguientes fines: a) identificación y autenticación, b) administración y gestión comercial, c) mejora del servicio, d) fines estadísticos, e) envío de notificaciones, promociones o publicidad, entre otros de MUNDO LIBRO, sus sociedades controladas y/o vinculadas (S.A. La Nación, Publirevistas S.A.; El Jardín en la Argentina S.A.; Covedisa S.A.; Eglam Argentina S.A.) y sus anunciantes. Los datos personales no serán difundidos ni empleados para un fin distinto o incompatible al tenido en cuenta al ser ingresados en la base. MUNDO LIBRO podrá emplear a otras compañías y/o personas físicas para llevar a cabo tareas o funciones en su nombre. Entre los ejemplos de ese tipo podemos mencionar el de enviar correo postal y electrónico, retirar información reiterativa de las listas de usuarios, analizar datos en forma estadística, etc. Dichas personas cuentan con acceso a la información personal necesaria para cumplir con sus tareas y funciones, pero no pueden utilizarla con fines distintos a los estipulados. Las bases de datos de MUNDO LIBRO se encuentran registradas en la Dirección Nacional de Protección de Datos Personales del Ministerio de Justicia y Derechos Humanos de la Presidencia de la Nación (República Argentina), en cumplimiento de lo dispuesto en el art. 3 de la Ley 25.326. El titular de los datos personales tiene la facultad de ejercer el derecho de acceso a los mismos en forma gratuita a intervalos no inferiores a 6 meses, salvo que se acredite un interés legítimo al efecto, conforme lo establecido en el art. 14, inc. 3 de la Ley 25.326. La DIRECCIÓN NACIONAL DE PROTECCIÓN DE DATOS PERSONALES, Órgano de Control de la Ley 25.326, tiene la atribución de atender las denuncias y reclamos que se interpongan con relación al incumplimiento de las normas sobre protección de datos personales. ​</p>
                </div>

                <div class="itemsTerms py-2">
                    <h2 class="h5 color-azul fw-bold">8. RESTRICCIONES DE USO</h2>
                    <p class="text-term color-azul"><b>8.1.-</b> Se permite únicamente un uso personal e intransferible de las claves de acceso al sitio. <b>8.2.-</b> Todos los contenidos de MUNDO LIBRO.com pertenecen a MUNDO LIBRO o, en su caso, a terceras personas y están protegidos por la legislación sobre propiedad intelectual. Ningún contenido del sitio, cualquiera que sea su naturaleza, podrá ser bajado, publicado, emitido, retransmitido directa o indirectamente en ningún medio o soporte para uso distinto del estrictamente personal. Por tanto, queda terminantemente prohibida su utilización con fines comerciales, su distribución, así como su modificación, alteración o descompilación. <b>8.3.-</b> Al acceder al sitio el usuario acepta no vender, no publicar, no distribuir, no retransmitir ni facilitar ningún acceso a los contenidos del sitio a terceros. <b>8.4.-</b> El usuario acepta no utilizar el sitio para ningún propósito ilegal. MUNDO LIBRO se reserva el derecho de restringir o cancelar el acceso al sitio si, en su opinión, el usuario utiliza el sitio para infringir alguna ley, violar derechos de terceros o incumplir las presentes condiciones de contratación. En caso de producirse descargas masivas de contenidos por parte de un usuario, MUNDO LIBRO se reserva el derecho de cancelar el acceso al sitio de dicho usuario, anular su suscripción, y/o adoptar las acciones legales que estime oportunas. MUNDO LIBRO no se responsabiliza de los nombres de usuarios que afectan a personas ajenas, están protegidos por marcas registradas u otras leyes o que resultaren vulgares u ofensivos. <b>8.5.-</b> MUNDO LIBRO puede facilitar enlaces, websites o servicios de otras compañías a través del sitio, así como facilitar al usuario la descarga de softwares de terceros. El usuario entiende y acepta que MUNDO LIBRO no controla y no es responsable de estos servicios y productos. <b>8.6.-</b> Los usuarios aceptan y reconocen que MUNDO LIBRO no controla, ni supervisa, ni asume responsabilidad alguna por la calidad, seguridad, características y demás elementos de los productos y/o servicios promocionados u ofrecidos en el sitio. Asimismo, aceptan y reconocen que MUNDO LIBRO no controla, ni supervisa, ni asume responsabilidad acerca de la veracidad y exactitud de la descripción efectuada por aquellos que promocionan u ofrecen sus productos o servicios (en adelante los "Oferentes"), ni acerca del cumplimiento de los requisitos legales para ofrecer y vender los productos o servicios, ni sobre la capacidad y legitimación de los Oferentes para promocionar, ofrecer y/o vender sus bienes o servicios. El material publicitario es propiedad de los solicitantes del espacio. MUNDO LIBRO no es responsable del contenido y al respecto rigen las mismas exclusiones que para el material editorial. <b>8.7.-</b> Se permite únicamente un uso personal e intransferible de las claves de acceso a los sitios.</p>
                </div>

                <div class="itemsTerms py-2">
                    <h2 class="h5 color-azul fw-bold">9. RESPONSABILIDAD DEL USUARIO</h2>
                    <p class="text-term color-azul"><b>9.1.-</b> El usuario es responsable de todos los datos, imágenes y manifestaciones que incluya en los formularios que envíe a MUNDO LIBRO así como del contenido de cualquier otra comunicación que emita a éste. El usuario responderá de la veracidad de los datos facilitados, reservándose MUNDO LIBRO el derecho a excluir de los servicios registrados a todo usuario que haya facilitado datos falsos, sin perjuicio de las demás acciones que procedan en derecho. <b>9.2.-</b> Mediante el envío del formulario de registro correspondiente, el usuario acepta las condiciones de registro aquí expuestas y se compromete a respetar el uso y las prohibiciones establecidas en las mismas. <b>9.3.-</b> El usuario acepta que, si sus datos de pago no permiten la facturación y/o cobro por parte de MUNDO LIBRO, el servicio o producto pedido no le sea otorgado. <b>9.4.-</b> Sólo podrán registrarse las personas físicas mayores de 18 años, en su propio nombre y derecho, o en el de la persona jurídica a la que represente con poder suficiente. <b>9.5.-</b> El usuario autoriza en forma gratuita a MUNDO LIBRO o a cualquier otro tercero previamente autorizado por MUNDO LIBRO a reutilizar y/o republicar en cualquier otro medio y/o en cualquier otra red social el comentario, reseña, o participación volcado en el sitio, con identificación del nombre de usuario. No obstante lo cual, MUNDO LIBRO se reserva el derecho de moderar o eliminar cualquier participación de los usuarios que pudiera ser ofensiva, ilegal, inadecuada o afectar el derecho de terceros. <b>9.6.-</b> Los Usuarios podrán registrarse a través de sus redes sociales (Gmail o Facebook) o a partir de su dirección de correo electrónico (email). El usuario podrá definir su nombre de usuario, y en caso de registrarse a través de Gmail o Facebook se tomará el nombre del usuario declarado a partir de los datos de la red social utilizada o los denunciados al registrar la dirección de correo electrónico. <b>9.7.-</b> Para los casos descriptos en el punto <b>9.6.</b>, anterior, el usuario podrá hacer uso de imágenes personales. MUNDO LIBRO no será responsable por las imágenes utilizadas por los usuarios, ni por los derechos de las mismas. Para cada usuario que no proporcione una imagen personal, se generará una imagen, determinada al azar (avatar).</p>
                </div>

                <div class="itemsTerms py-2">
                    <h2 class="h5 color-azul fw-bold">10. RESPONSABILIDAD DE MUNDO LIBRO</h2>
                    <p class="text-term color-azul"><b>10.1.- </b>MUNDO LIBRO se compromete a poner a disposición del cliente en el sitio la información necesaria relativa a los productos que ofrece y las condiciones de contratación. <b>10.2.-</b> El usuario acepta que el acceso al sitio y el contenido del mismo es el existente en cada momento. MUNDO LIBRO no aceptará reclamación alguna por los contenidos, actualizaciones o conexiones al sitio. <b>10.3.-</b> MUNDO LIBRO hará todo lo posible por asegurar de buena fe, con todos los medios a su alcance, el acceso al servicio contratado por el usuario. No obstante lo anterior, MUNDO LIBRO no se responsabiliza de los fallos técnicos de conexión de red que puedan provocar daños en los equipos, impedir la conexión o limitar total o parcialmente el acceso del usuario al sitio. MUNDO LIBRO no se responsabilizará de las averías que se produzcan por las empresas suministradoras de servicio y que puedan impedir el acceso al sitio y en ningún caso asegurará el reembolso del importe pagado en caso de reclamación. MUNDO LIBRO únicamente responderá por aquellos daños o perjuicios que le puedan ser imputados a MUNDO LIBRO a título de dolo o culpa grave. En dichos supuestos de responsabilidad de MUNDO LIBRO, la indemnización no comprenderá el lucro cesante.</p>
                </div>

                <div class="itemsTerms py-2">
                    <h2 class="h5 color-azul fw-bold">11. RESOLUCIÓN DEL CONTRATO</h2>
                    <p class="text-term color-azul"><b>11.1.-</b> En caso de corresponder, MUNDO LIBRO se reserva el derecho a retirar de forma inmediata el acceso al servicio y a los contenidos pagos contratados a aquellos clientes que a criterio de MUNDO LIBRO contravengan lo dispuesto en las presentes condiciones, sin posibilidad de reembolso en caso de haberse efectuado el pago. Concretamente, MUNDO LIBRO podrá anular la contratación: a.- Cuando el acceso se utilice con fines ilegítimos, incluyendo por tales los enumerados en las presentes Condiciones Generales y en el Reglamento General. b.- Cuando los datos de cobro proporcionados en la contratación sean erróneos o imposibiliten la facturación y/o cobro del servicio contratado o del bien adquirido. c.- En caso de inutilización prolongada y continua o inadecuada de cualquiera de los contenidos o servicios que hubieran sido contratados, indicando en este caso al usuario, claramente los términos en los que aplicará dicha cancelación. d.- En caso de usos fraudulentos del producto o contrarios a la buena fe. <b>11.2.-</b> En caso de corresponder, el usuario tiene derecho a revocar la contratación de servicios o productos del sitio durante el plazo de DIEZ (10) días corridos, contados a partir de la fecha en que se entregue el producto o se celebre el contrato, lo último que ocurra, sin responsabilidad alguna. Esta facultad no puede ser dispensada ni renunciada. El usuario deberá comunicar fehacientemente dicha revocación a MUNDO LIBRO. Adquisición de productos: En caso de corresponder, los gastos de devolución son por cuenta de MUNDO LIBRO. Para ejercer el derecho de revocación el consumidor deberá poner el producto a disposición de MUNDO LIBRO sin haberlo usado y manteniéndolo en el mismo estado en que lo recibió. De verificarse estas condiciones MUNDO LIBRO restituirá al usuario los importes percibidos.</p>
                </div>

                <div class="itemsTerms py-2">
                    <h2 class="h5 color-azul fw-bold">12. CONTRATO</h2>
                    <p class="text-term color-azul">En caso de corresponder, el documento entre el usuario y MUNDO LIBRO estará compuesto por las presentes Condiciones Generales, el formulario enviado por el usuario con sus datos personales y de pago, y los datos ubicados en MUNDO LIBRO que completan el presente documento, prevaleciendo frente a cualquier otro acuerdo verbal o escrito previo o simultáneo.</p>
                </div>

                <div class="itemsTerms py-2">
                    <h2 class="h5 color-azul fw-bold">13. LEY APLICABLE Y JURISDICCIÓN</h2>
                    <p class="text-term color-azul">El presente contrato se interpretará y regirá conforme a la legislación argentina. LIBOOKS y el usuario se comprometen a intentar resolver de manera amistosa cualquier desacuerdo que pudiera surgir en el desarrollo del presente Contrato, previamente a acudir a la jurisdicción contemplada.</p>
                </div>
            </div>
            
        </div>
    </div>
</main>